const commonItems = ['','']
const uncommonItems = ['','']
const rareItems = ['','']
const epiccommonItems = ['','']
const legendaryItems = ['','']
const exoticItems = ['','']
const mithicItems = ['','']
const goddlyItems = ['','']
